spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/gforms
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
jwt:
  secret: some-big-secret
